# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout, QPushButton, QLineEdit

style = """
 QPushButton{
    height:30px;
    background-color: transparent;
    color: grey;
    border: 2px solid #555555;
    border-radius: 6px;
 }
"""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)

        # 禁止拉伸窗口大小

        font = QtGui.QFont()
        font.setFamily("Arial")  # 括号里可以设置成自己想要的其它字体
        font.setPointSize((2/100)*MainWindow.width())  # 括号里的数字可以设置成自己想要的字体大小
        # mywin = QVBoxLayout()

        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect((2/16)*MainWindow.width(), (1/2)*MainWindow.height()
                                            , (1/5)*MainWindow.width(), (1/16)*MainWindow.height()))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect((2/16)*MainWindow.width(), (3/5)*MainWindow.height()
                                            , (1/5)*MainWindow.width(), (1/16)*MainWindow.height()))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.un_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.un_edit.setGeometry(QtCore.QRect((2/16)*MainWindow.width()+(1/5)*MainWindow.width(), (1/2)*MainWindow.height()
                                            , (9/20)*MainWindow.width(), (1/16)*MainWindow.height()))
        self.un_edit.setObjectName("un_edit")
        self.pwd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd_edit.setGeometry(QtCore.QRect((2/16)*MainWindow.width()+(1/5)*MainWindow.width(), (3/5)*MainWindow.height()
                                            , (9/20)*MainWindow.width(), (1/16)*MainWindow.height()))
        self.pwd_edit.setObjectName("pwd_edit")
        self.pwd_edit.setEchoMode(QLineEdit.Password)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 20, 101, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect((2/16)*MainWindow.width()+(1/5)*MainWindow.width(), (7/10)*MainWindow.height()
                                            , (9/20)*MainWindow.width(), (1/16)*MainWindow.height()))
        self.login_btn.setObjectName("login_btn")
        self.label.setFont(font)
        self.label_2.setFont(font)
        self.label_3.setFont(font)
        self.un_edit.setFont(font)
        self.pwd_edit.setFont(font)
        self.login_btn.setStyleSheet(style)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 359, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "账号"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        # self.label_3.setText(_translate("MainWindow", "用户登录"))
        self.login_btn.setText(_translate("MainWindow", "登录"))


